import { Code2 } from 'lucide-react';

export const techNameMap: Record<string, string> = {
  'react': 'react',
  'react.js': 'react',
  'reactjs': 'react',
  'node.js': 'nodedotjs',
  'node': 'nodedotjs',
  'nodejs': 'nodedotjs',
  'postgresql': 'postgresql',
  'postgres': 'postgresql',
  'mongodb': 'mongodb',
  'next.js': 'nextdotjs',
  'nextjs': 'nextdotjs',
  'next': 'nextdotjs',
  'typescript': 'typescript',
  'ts': 'typescript',
  'javascript': 'javascript',
  'js': 'javascript',
  'tailwind css': 'tailwindcss',
  'tailwindcss': 'tailwindcss',
  'tailwind': 'tailwindcss',
  'python': 'python',
  'docker': 'docker',
  'vue': 'vuedotjs',
  'vue.js': 'vuedotjs',
  'vuejs': 'vuedotjs',
  'angular': 'angular',
  'php': 'php',
  'laravel': 'laravel',
  'html': 'html5',
  'html5': 'html5',
  'css': 'css3',
  'css3': 'css3',
  'git': 'git',
  'github': 'github',
  'firebase': 'firebase',
  'supabase': 'supabase',
  'redis': 'redis',
  'mysql': 'mysql',
  'graphql': 'graphql',
  'figma': 'figma',
  'express': 'express',
  'express.js': 'express',
  'spring boot': 'springboot',
  'springboot': 'springboot',
  'nest.js': 'nestjs',
  'nestjs': 'nestjs',
  'android': 'android',
  'ios': 'ios',
  'flutter': 'flutter',
  'kubernetes': 'kubernetes',
  'k8s': 'kubernetes',
  'google cloud': 'googlecloud',
  'gcp': 'googlecloud',
  'rust': 'rust',
  'go': 'go',
  'golang': 'go',
  'swift': 'swift',
  'kotlin': 'kotlin',
  'wordpress': 'wordpress',
  'stripe': 'stripe',
  'solidity': 'solidity',
  'ethereum': 'ethereum',
  'prisma': 'prisma',
  'framer': 'framer',
  'framer motion': 'framer',
  'vercel': 'vercel',
  'greensock': 'greensock',
  'gsap': 'greensock',
  'react router': 'reactrouter',
  'redux': 'redux',
  'material ui': 'mui',
  'mui': 'mui',
  'chakra ui': 'chakraui',
  'bootstrap': 'bootstrap',
  'sass': 'sass',
  'vite': 'vite',
  'jest': 'jest',
  'cypress': 'cypress',
  'apollo': 'apollographql',
  'sanity': 'sanity',
  'strapi': 'strapi',
  'contentful': 'contentful',
  'netlify': 'netlify',
  'heroku': 'heroku',
  'java': 'java',
  'aws': 'amazonaws',
  'azure': 'microsoftazure'
};

export const techColorMap: Record<string, string> = {
  'react': '#61DAFB',
  'nodedotjs': '#339933',
  'postgresql': '#4169E1',
  'mongodb': '#47A248',
  'nextdotjs': '#000000',
  'typescript': '#3178C6',
  'javascript': '#F7DF1E',
  'tailwindcss': '#06B6D4',
  'python': '#3776AB',
  'docker': '#2496ED',
  'amazonaws': '#FF9900',
  'vuedotjs': '#4FC08D',
  'angular': '#DD0031',
  'java': '#007396',
  'php': '#777BB4',
  'laravel': '#FF2D20',
  'html5': '#E34F26',
  'css3': '#1572B6',
  'git': '#F05032',
  'github': '#181717',
  'firebase': '#FFCA28',
  'supabase': '#3ECF8E',
  'redis': '#DC382D',
  'mysql': '#4479A1',
  'graphql': '#E10098',
  'figma': '#F24E1E',
  'express': '#000000',
  'springboot': '#6DB33F',
  'nestjs': '#E0234E',
  'android': '#3DDC84',
  'ios': '#000000',
  'flutter': '#02569B',
  'kubernetes': '#326CE5',
  'googlecloud': '#4285F4',
  'microsoftazure': '#0089D6',
  'rust': '#000000',
  'go': '#00ADD8',
  'swift': '#FA7343',
  'kotlin': '#0095D5',
  'wordpress': '#21759B',
  'stripe': '#008CDD',
  'solidity': '#363636',
  'ethereum': '#3C3C3D',
  'prisma': '#2D3748',
  'framer': '#0055FF',
  'vercel': '#000000',
  'greensock': '#88CE02',
  'reactrouter': '#CA4245',
  'redux': '#764ABC',
  'mui': '#007FFF',
  'chakraui': '#319795',
  'bootstrap': '#7952B3',
  'sass': '#CC6699',
  'vite': '#646CFF',
  'jest': '#C21325',
  'cypress': '#17202C',
  'apollographql': '#311C87',
  'sanity': '#F03E2F',
  'strapi': '#2F2E8B',
  'contentful': '#2478CC',
  'netlify': '#00C7B7',
  'heroku': '#430098'
};

export default function TechIconRenderer({ iconName, size = 16, color }: { iconName: string, size?: number, color?: string }) {
  if (!iconName) return <Code2 size={size} color={color} />;

  const normalizedName = iconName.toLowerCase().trim();
  const simpleIconSlug = techNameMap[normalizedName];

  if (!simpleIconSlug) {
    return <Code2 size={size} color={color || '#6b7280'} />;
  }

  const iconColor = color || techColorMap[simpleIconSlug] || '#6b7280';
  const hex = iconColor.replace('#', '');
  
  return (
    <img 
      src={`https://cdn.simpleicons.org/${simpleIconSlug}/${hex}`} 
      width={size} 
      height={size} 
      alt={iconName} 
      style={{ display: 'inline-block' }} 
      loading="lazy"
    />
  );
}
